Add more extensive testing on travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,3 +1,4 @@
+sudo: required
 language: c
 
 cache:
@@ -9,17 +10,23 @@ env:
   global:
     # Encrypted COVERITY_SCAN_TOKEN
     - secure: KKhG29VpIOr5mq9xHptpDSfFEcSRKB8BX4e5zL0VQNJGkrNAHJ7ba+boHKEmSJJ1fZvHC18XOb886BIsn0i+lFrVymYDR8L8ca3e/k26LktnqMn76ORK1WYkD1fiRg3lX25v/j0TkoLB7pmDnMhZyGzg20675V1sHbl/KCO1LJI=
-    - AUTOQEMU_NICS=''
   matrix:
     - TEMPLATE=arm/qemu
     - TEMPLATE=arm/stm32_f4
     - TEMPLATE=x86/qemu
+    - TEMPLATE=x86/smp
     - TEMPLATE=x86/test/lang
+    - TEMPLATE=x86/test/fs
+    - TEMPLATE=x86/test/net
+    - TEMPLATE=x86/test/packetdrill
+    - TEMPLATE=sparc/qemu
+    - TEMPLATE=mips/qemu
+    - TEMPLATE=ppc/qemu
+    - TEMPLATE=microblaze/petalogix
+    - TEMPLATE=usermode86/debug
 matrix:
   include:
   - env: UNCRUSTIFY
-    before_install:
-      - true
     install:
       - SRC=$PWD/uncrustify INSTALL=$PWD/uncrustify/dist ./scripts/codestyle/install_uncrustify.sh
     before_script:
@@ -28,27 +35,10 @@ matrix:
       - uncrustify -v
       - ./scripts/codestyle/travis_uncrustify.sh
 
-before_install:
-  - travis_retry sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
-  - travis_retry sudo apt-get update -qq
-  - echo 'travis variables'
-  - echo $TRAVIS_COMMIT
-  - echo $TRAVIS_PULL_REQUEST
-  - echo $TRAVIS_PULL_REQUEST_SHA
-
-# TODO make it template-specific
-install:
-  - travis_retry sudo apt-get install -qq gcc-arm-embedded
-  - travis_retry sudo apt-get install -qq gcc-multilib
-  - travis_retry sudo apt-get install -qq u-boot-tools
-  - travis_retry sudo apt-get install -qq qemu qemu-system
-
 before_script:
-  - unset CC
-  - export CC
-  - make confload-"$TEMPLATE"
-  - sed -ie '/eth0\|http/d' conf/start_script.inc  # FIXME
-  - make buildgen  # Make as much as possible before the actual build step.
+  - set -e # make this script fail as soon as any individual command fail
+  - sudo modprobe nfsd
+  - DOCKER_START_WAIT_TIME_SEC=60 ./scripts/docker/docker_start.sh embox/emdocker-test
   - |
     if [ "${COVERITY_SCAN_BRANCH}" != 1 ]
     then
@@ -58,7 +48,11 @@ before_script:
     fi
 
 script:
-  - run make && run ./scripts/continuous/run.sh "$TEMPLATE"
+  - set -e # make this script fail as soon as any individual command fail
+  - . ./scripts/docker/docker_rc.sh
+  - dr make confload-"$TEMPLATE"
+  - run dr make
+  - run dr ./scripts/continuous/run.sh "$TEMPLATE"
 
 addons:
   coverity_scan:
