WIP

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,74 +4,88 @@ on: [push]
 
 jobs:
 
-  buildgen:
+  test:
     runs-on: ubuntu-latest
-    #container: embox/emdocker
-    steps:
-      - uses: actions/checkout@v1
-      - run: make confload-x86/qemu
-      - run: make buildgen
-      - uses: actions/upload-artifact@v1
-        with:
-          name: mk-cache
-          path: mk/.cache
-  ci:
-    needs: buildgen
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        template:
-          - aarch64/qemu
-          - arm/qemu
-          - arm/stm32f4-discovery
-          - x86/qemu
-          - x86/smp
-          - x86/user_apps
-          - x86/qt-app
-          - x86/test/lang
-          - x86/test/net
-          - x86/test/units
-          - x86/test/packetdrill
-          - x86/test/qt-vnc
-          - sparc/qemu
-          - mips/qemu
-          - ppc/qemu
-          - microblaze/qemu
-          - usermode86/debug
-    container:
-      image: embox/emdocker-test
-      options: --privileged
-    steps:
-      - uses: actions/checkout@v1
-      - uses: actions/download-artifact@v1
-        with:
-          name: mk-cache
-          path: mk/.cache
-      - run: |
-          touch mk/.cache/mk/*
-          find  mk/.cache/mybuild/files | xargs touch
-          touch mk/.cache/mybuild/myfiles-model.mk
-          touch mk/.cache/mybuild/myfiles-list.mk
-      - run: make confload-${{matrix.template}}
-      - run: make
-      - run: ./scripts/continuous/run.sh ${{matrix.template}}
+    run: |
+      set -x
+      A=google.com
+      tracepath $A || true
+      traceroute $A || true
+      cat /etc/resolv.conf || true
+      ping -c 1 $A || true
+      getent hosts $A || true
+      getent ahosts $A || true
+      getent ahostsv4 $A || true
+      dig +short $A || true
 
-  # need to manage container by hand because of modprobe below
-  ci-x86-fs:
-    needs: buildgen
-    runs-on: ubuntu-16.04 # on ubuntu 18.04 NFS write test results in "RPC: Can't decode result"
-    steps:
-      - uses: actions/checkout@v1
-      - uses: actions/download-artifact@v1
-        with:
-          name: mk-cache
-          path: mk/.cache
-      - name: Build and test
-        run: |
-          sudo modprobe nfsd
-          DOCKER_START_WAIT_TIME_SEC=60 ./scripts/docker/docker_start.sh embox/emdocker-test
-          . ./scripts/docker/docker_rc.sh
-          dr make confload-x86/test/fs
-          dr make
-          dr ./scripts/continuous/run.sh x86/test/fs
+  #buildgen:
+    #runs-on: ubuntu-latest
+    ##container: embox/emdocker
+    #steps:
+      #- uses: actions/checkout@v1
+      #- run: make confload-x86/qemu
+      #- run: make buildgen
+      #- uses: actions/upload-artifact@v1
+        #with:
+          #name: mk-cache
+          #path: mk/.cache
+  #ci:
+    #needs: buildgen
+    #runs-on: ubuntu-latest
+    #strategy:
+      #fail-fast: false
+      #matrix:
+        #template:
+          #- aarch64/qemu
+          #- arm/qemu
+          #- arm/stm32f4-discovery
+          #- x86/qemu
+          #- x86/smp
+          #- x86/user_apps
+          #- x86/qt-app
+          #- x86/test/lang
+          #- x86/test/net
+          #- x86/test/units
+          #- x86/test/packetdrill
+          #- x86/test/qt-vnc
+          #- sparc/qemu
+          #- mips/qemu
+          #- ppc/qemu
+          #- microblaze/qemu
+          #- usermode86/debug
+    #container:
+      #image: embox/emdocker-test
+      #options: --privileged
+    #steps:
+      #- uses: actions/checkout@v1
+      #- uses: actions/download-artifact@v1
+        #with:
+          #name: mk-cache
+          #path: mk/.cache
+      #- run: |
+          #touch mk/.cache/mk/*
+          #find  mk/.cache/mybuild/files | xargs touch
+          #touch mk/.cache/mybuild/myfiles-model.mk
+          #touch mk/.cache/mybuild/myfiles-list.mk
+      #- run: make confload-${{matrix.template}}
+      #- run: make
+      #- run: ./scripts/continuous/run.sh ${{matrix.template}}
+
+  ## need to manage container by hand because of modprobe below
+  #ci-x86-fs:
+    #needs: buildgen
+    #runs-on: ubuntu-16.04 # on ubuntu 18.04 NFS write test results in "RPC: Can't decode result"
+    #steps:
+      #- uses: actions/checkout@v1
+      #- uses: actions/download-artifact@v1
+        #with:
+          #name: mk-cache
+          #path: mk/.cache
+      #- name: Build and test
+        #run: |
+          #sudo modprobe nfsd
+          #DOCKER_START_WAIT_TIME_SEC=60 ./scripts/docker/docker_start.sh embox/emdocker-test
+          #. ./scripts/docker/docker_rc.sh
+          #dr make confload-x86/test/fs
+          #dr make
+          #dr ./scripts/continuous/run.sh x86/test/fs
